# Generated by Django 5.1.6 on 2025-02-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0003_alter_buses_start_alter_buses_end_delete_mrtstation"),
    ]

    operations = [
        migrations.CreateModel(
            name="MRTStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=3)),
                ("address", models.CharField(max_length=64)),
                ("color", models.CharField(max_length=64)),
            ],
        ),
    ]
