# Generated by Django 5.1.6 on 2025-03-16 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stronger", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("note", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RUN", "run"),
                            ("WALK", "walk"),
                            ("SWIM", "swim"),
                            ("INCLINE", "incline"),
                            ("CHEST", "chest"),
                            ("BACK", "back"),
                            ("SHOULDERS", "shoulder"),
                            ("ARMS", "arms"),
                            ("CORE", "core"),
                            ("LEGS", "leg"),
                            ("OTHERS", "Others"),
                        ],
                        default="OTHERS",
                        max_length=64,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Set",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("duration", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NOT STARTED", "Not Started"),
                            ("COMPLETED", "Completed"),
                            ("INCOMPLETED", "Incompleted"),
                        ],
                        default="NOT STARTED",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("reps", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="stronger.exercise",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("desc", models.CharField(max_length=500)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT STARTED", "Not Started"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="NOT STARTED",
                        max_length=64,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="exercise",
            name="workout",
            field=models.ManyToManyField(
                related_name="exercises_included", to="stronger.workout"
            ),
        ),
    ]
