# Generated by Django 5.1.6 on 2025-03-17 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stronger", "0002_exercise_set_workout_exercise_workout"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workout",
            old_name="date",
            new_name="start_date",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="workout",
        ),
        migrations.AddField(
            model_name="workout",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workout",
            name="exercises",
            field=models.ManyToManyField(
                related_name="workouts", to="stronger.exercise"
            ),
        ),
        migrations.CreateModel(
            name="WorkoutTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "exercises",
                    models.ManyToManyField(
                        related_name="templates", to="stronger.exercise"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
