# Generated by Django 5.1.6 on 2025-03-23 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stronger", "0003_rename_date_workout_start_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="set",
            old_name="session",
            new_name="exercise",
        ),
        migrations.RemoveField(
            model_name="set",
            name="status",
        ),
        migrations.RemoveField(
            model_name="workout",
            name="status",
        ),
    ]
