# Generated by Django 5.1.6 on 2025-03-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stronger", "0004_rename_session_set_exercise_remove_set_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="set",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="set",
            name="desc",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
