# Generated by Django 5.1.6 on 2025-04-01 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "stronger",
            "0006_rename_note_exercise_exercise_note_remove_set_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workouttemplate",
            name="exercises",
        ),
        migrations.CreateModel(
            name="ExerciseTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_exercises",
                        to="stronger.exercise",
                    ),
                ),
                (
                    "workout_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises_template",
                        to="stronger.workouttemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SetTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("desc", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("duration", models.PositiveIntegerField(blank=True, null=True)),
                ("reps", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "exercise_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="set_templates",
                        to="stronger.exercisetemplate",
                    ),
                ),
            ],
        ),
    ]
