# Generated by Django 5.1.6 on 2025-04-05 02:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stronger", "0008_workouttemplate_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="workouttemplate",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
