# Generated by Django 5.1.6 on 2025-04-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stronger", "0009_workouttemplate_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="workouttemplate",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
