# Generated by Django 5.2 on 2025-04-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stronger", "0010_workouttemplate_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("DURATION", "duration"), ("WEIGHT", "weight")],
                default="weight",
                max_length=64,
                null=True,
            ),
        ),
    ]
