# Generated by Django 5.2 on 2025-04-11 06:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stronger", "0011_exercise_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="set",
            name="completed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="workout",
            name="completed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
