# Generated by Django 5.2 on 2025-04-20 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plog", "0002_alter_session_desc_logtemplate_exercisetemplate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional. Reference to the template used to create this log",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logs_created_from_template",
                to="plog.logtemplate",
            ),
        ),
    ]
