# Generated by Django 5.2 on 2025-04-22 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plog", "0004_remove_exercise_notes_exercisenote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercisenote",
            name="exercise",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="note",
                to="plog.exercise",
            ),
        ),
    ]
