# Generated by Django 5.2 on 2025-04-24 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plog", "0005_alter_exercisenote_exercise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercisenote",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="plog.exercise",
            ),
        ),
    ]
