# Generated by Django 5.1.6 on 2025-02-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Buses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.CharField(max_length=64)),
                ("end", models.CharField(max_length=64)),
                ("stops", models.IntegerField()),
            ],
        ),
    ]
