# Generated by Django 5.1.6 on 2025-02-11 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MRTStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=3)),
                ("address", models.CharField(max_length=64)),
                ("color", models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name="buses",
            name="end",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arrival",
                to="buses.mrtstation",
            ),
        ),
        migrations.AlterField(
            model_name="buses",
            name="start",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departure",
                to="buses.mrtstation",
            ),
        ),
    ]
