# Generated by Django 5.1.6 on 2025-02-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0002_mrtstation_alter_buses_end_alter_buses_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buses",
            name="start",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="buses",
            name="end",
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name="MRTStation",
        ),
    ]
