# Generated by Django 5.1.6 on 2025-02-12 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0004_mrtstation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buses",
            name="end",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arrival",
                to="buses.mrtstation",
            ),
        ),
        migrations.AlterField(
            model_name="buses",
            name="start",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departure",
                to="buses.mrtstation",
            ),
        ),
    ]
